package cr.ac.una.icai.sipreli.clases;
// Generated May 19, 2016 3:09:41 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements Serializable {


     private int isbn;
     private String nombre;
     private String autor;
     private Integer anoPublicacion;
     private String editorial;
     private String genero;

    public Libro() {
    }

	
    public Libro(int isbn) {
        this.isbn = isbn;
    }
   
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Integer getAnoPublicacion() {
        return this.anoPublicacion;
    }
    
    public void setAnoPublicacion(Integer anoPublicacion) {
        this.anoPublicacion = anoPublicacion;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }


    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + this.isbn;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Libro other = (Libro) obj;
        if (this.isbn != other.isbn) {
            return false;
        }
        return true;
    }

}


