package cr.ac.una.icai.sipreli.clases;
// Generated May 19, 2016 3:09:41 PM by Hibernate Tools 4.3.1

import java.util.Objects;
/**
 * PrestamoId generated by hbm2java
 */
public class PrestamoId  implements java.io.Serializable {


     private Estudiante elEstudiante;
     private Libro elLibro;

    public PrestamoId() {
        this.elEstudiante = new Estudiante();
        this.elLibro = new Libro();
    }

    public Estudiante getElEstudiante() {
        return elEstudiante;
    }

    public void setElEstudiante(Estudiante elEstudiante) {
        this.elEstudiante = elEstudiante;
    }

    public Libro getElLibro() {
        return elLibro;
    }

    public void setElLibro(Libro elLibro) {
        this.elLibro = elLibro;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.elEstudiante);
        hash = 41 * hash + Objects.hashCode(this.elLibro);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PrestamoId other = (PrestamoId) obj;
        if (!Objects.equals(this.elEstudiante, other.elEstudiante)) {
            return false;
        }
        if (!Objects.equals(this.elLibro, other.elLibro)) {
            return false;
        }
        return true;
    }
}


