package cr.ac.una.icai.sipreli.clases;
// Generated May 19, 2016 3:09:41 PM by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * UsuarioLogin generated by hbm2java
 */
public class UsuarioLogin  implements java.io.Serializable {


     private String usuario;
     private String contrasena;

    public UsuarioLogin() {
    }

	
    public UsuarioLogin(String usuario) {
        this.usuario = usuario;
    }
    public UsuarioLogin(String usuario, String contrasena) {
       this.usuario = usuario;
       this.contrasena = contrasena;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.usuario);
        hash = 19 * hash + Objects.hashCode(this.contrasena);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsuarioLogin other = (UsuarioLogin) obj;
        if (!Objects.equals(this.usuario, other.usuario)) {
            return false;
        }
        if (!Objects.equals(this.contrasena, other.contrasena)) {
            return false;
        }
        return true;
    }
}


